steps_input = input("Enter the number of steps taken each day in a month (separated by spaces): ")
steps = list(map(int, steps_input.split()))
highest_steps = max(steps)
lowest_steps = min(steps)
average_steps = sum(steps) / len(steps)
sorted_steps = sorted(steps, reverse=True)
print(f"Highest Steps: {highest_steps}")
print(f"Lowest Steps: {lowest_steps}")
print(f"Average Steps: {average_steps:.2f}")
print(f"Steps in Descending Order: {sorted_steps}")